name: APK Build

# Run the workflow when commits are pushed on main or when a PR is modified
on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
        description: "Tag Name"
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'

jobs:
  build:
    name: APK Build
    # Execute the CI on the course's runners
    runs-on: ubuntu-latest

    steps:
      # First step : Checkout the repository on the runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis (if we use Sonar Later)

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Create signing files
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          echo "MAPS_API_KEY=$MAPS_API_KEY" > ./local.properties
          echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
          echo $KEYSTORE | base64 -di > ./keystore.jks
          echo $KEYSTORE_PROPERTIES | base64 -di > ./keystore.properties

      - name: Building Release APK
        run: ./gradlew assembleRelease

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-v${{ inputs.tag_name }}
          path: ${{ steps.releaseApk.outputs.apkfile }}
